let stockProductos = [
    {id: 1, nombre: "Zapato 1", tipo: "Zapato", cantidad: 1, desc: "Un estilo que va contigo", precio: 120, talle: "9", img: './img/Zapato1.jpg'},
    {id: 2, nombre: "Zapato 2", tipo: "Zapato", cantidad: 1, desc: "Un estilo que va contigo", precio: 110, talle: "10", img: './img/Zapato2.jpg'},
    {id: 3, nombre: "Zapato 3", tipo: "Zapato", cantidad: 1, desc: "Un estilo que va contigo", precio: 200, talle: "10.5", img: './img/Zapato3.jpg'},
    {id: 4, nombre: "Zapato 4", tipo: "Zapato", cantidad: 1, desc: "Un estilo que va contigo", precio: 400, talle: "11", img: './img/Zapato4.jpg'},
    {id: 5, nombre: "Zapato 5", tipo: "Zapato", cantidad: 1, desc: "Un estilo que va contigo", precio: 200, talle: "12", img: './img/Zapato5.jpg'},
    {id: 6, nombre: "Zapato 6", tipo: "Zapato", cantidad: 1, desc: "Un estilo que va contigo", precio: 150, talle: "8", img: './img/Zapato6.jpg'},
    {id: 7, nombre:  "Chanclas 1", tipo: "Chanclas", cantidad: 1, desc: "Un estilo que va contigo", precio: 50, talle: "8", img: './img/Chanclas1.jpg'},
    {id: 8, nombre:  "Chanclas 2", tipo: "Chanclas", cantidad: 1, desc: "Un estilo que va contigo", precio: 50, talle: "9", img: './img/Chanclas2.JPG'},
    {id: 9, nombre:  "Chanclas 3", tipo: "Chanclas", cantidad: 1, desc: "Un estilo que va contigo", precio: 50, talle: "10", img: './img/Chanclas3.jpg'},
    {id: 10, nombre: "Chanclas 4", tipo: "Chanclas", cantidad: 1, desc: "Un estilo que va contigo", precio: 70, talle: "10.5", img: './img/Chanclas4.jpg'},
    {id: 11, nombre: "Chanclas 5", tipo: "Chanclas", cantidad: 1,desc: "Un estilo que va contigo", precio: 60, talle: "11", img: './img/Chanclas5.jpg'},
    {id: 12, nombre: "Chanclas 6", tipo: "Chanclas", cantidad: 1, desc: "Un estilo que va contigo", precio: 80, talle: "12", img: './img/Chanclas6.jpg'},
    {id: 13, nombre: "camisa 1", tipo: "camisa", cantidad: 1, desc: "Una camisa que va con tu estilo", precio: 90, talle: "XS", img: './img/Camisa1.jpg'},
    {id: 14, nombre: "camisa 2", tipo: "camisa", cantidad: 1, desc: "Una camisa que va con tu estilo", precio: 140, talle: "S", img: './img/Camisa2.jpg'},
    {id: 15, nombre: "camisa 3", tipo: "camisa", cantidad: 1, desc: "Una camisa que va con tu estilo", precio: 70, talle: "M", img: './img/Camisa3.jpg'},
    {id: 16, nombre: "camisa 4", tipo: "camisa", cantidad: 1, desc: "Una camisa que va con tu estilo", precio: 77, talle: "L", img: './img/Camisa4.jpg'},
    {id: 17, nombre: "camisa 5", tipo: "camisa", cantidad: 1, desc: "Una camisa que va con tu estilo", precio: 34, talle: "XL", img: './img/Camisa5.jpg'},
    {id: 18, nombre: "camisa 6", tipo: "camisa", cantidad: 1, desc: "Una camisa que va con tu estilo", precio: 150, talle: "XXL", img: './img/Camisa6.jpg'},
    {id: 19, nombre: "Short 1", tipo: "Short", cantidad: 1, desc: "Una pantalon que va con tu estilo", precio: 160, talle: "28", img: './img/Short1.jpg'},
    {id: 20, nombre: "Short 2", tipo: "Short", cantidad: 1, desc: "Una pantalon que va con tu estilo", precio: 320, talle: "30", img: './img/Short2.jpg'},
    {id: 21, nombre: "Short 3", tipo: "Short", cantidad: 1, desc: "Una pantalon que va con tu estilo", precio: 200, talle: "32", img: './img/Short3.jpg'},
    {id: 22, nombre: "Short 4", tipo: "Short", cantidad: 1, desc: "Una pantalon que va con tu estilo", precio: 50, talle: "34", img: './img/Short4.jpg'},
    {id: 23, nombre: "Short 5", tipo: "Short", cantidad: 1, desc: "Una pantalon que va con tu estilo", precio: 170, talle: "36", img: './img/Short5.jpg'},
    {id: 24, nombre: "Short 6", tipo: "Short", cantidad: 1, desc: "Una pantalon que va con tu estilo", precio: 80, talle: "40", img: './img/Short6.jpg'},
]